#!/bin/sh

B='#00000000'  # blank
C='#368DFF22'  # clear ish
D='#368DFFcc'  # default
T='#ffffffff'  # text
W='#ffffffbb'  # wrong
V='#ffffffff'  # verifying
red='#CC0000ff'

i3lock \
--insidevercolor=$C   \
--ringvercolor=$D     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$red   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T        \
--wrongcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
\
--screen 1            \
--blur 5              \
# --clock               \
--indicator           \
# --timestr="%H:%M:%S"  \
--datestr="%A, %m %Y" \
--radius=200	      \
--datesize=25	      \
--timesize=65	      \
--ring-width=10       \
--datepos="ix:iy+40"
#--textsize=25	      \
# --veriftext="Drinking verification can..."
# --wrongtext="Nope!"
#--textsize=30 \
#--modsize=20 \
# --timefont=comic-sans
# --datefont=monofur
# etc

