#!/bin/sh

killall bspswallow
rofi -show run

while pidof rofi; do continue
done

bspc subscribe node_add | while read -r event; do
sh $HOME/scripts/bspswallow & exit
done

#sleep 2
#sh $HOME/scripts/bspswallow & exit

