#!/usr/bin/env bash

# Try to get a list of PIDs for appropriate conky's
runningConkys=$(pgrep --full sidepanes.conkyrc)

case $1 in
  on)
    if [[ -z "$runningConkys" ]]; then
      # start conky
      conky -q -c ~/.config/conky/sidepanes/sidepanes.conkyrc &
    fi
    ;;
  off)
    echo "$runningConkys" | xargs -n 1 kill -15
    ;;
esac

