#!/bin/bash

# You can call this script like this:
# $./volume.sh up
# $./volume.sh down
# $./volume.sh mute

function get_volume {
    amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
    amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

case $1 in
    up)
	# Set the volume on (if it was muted)
	amixer -D pulse set Master on > /dev/null
	# Up the volume (+ 5%)
  amixer -D pulse sset Master 10%+ > /dev/null && echo $(amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1)  > /tmp/xobpipe
	;;
    down)
	amixer -D pulse set Master on > /dev/null
  amixer -D pulse sset Master 10%- > /dev/null && echo $(amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1) > /tmp/xobpipe
	;;
    mute)
    	# Toggle mute
	# amixer -D pulse set Master 1+ toggle > /dev/null
  if amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 3 | cut -d ']' -f 1 | grep -q 'on'; then
    amixer -D pulse set Master off && echo $(amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1)! > /tmp/xobpipe
  else
    amixer -D pulse set Master on && echo $(amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1) > /tmp/xobpipe
  fi
	;;
esac

